/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取服务端当前命理日的已发布内容
         * @description 服务端按 `Asia/Shanghai` 一次性计算完整 `requestContext`。
         *     网页不得使用设备时钟重新计算 `civilDate`、`fortuneDate` 或 `shichen`。
         */
        get: operations["getToday"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/daily/{fortuneDate}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取指定命理日当前安全的公开内容
         * @description 用于分享落地页和既有日期链接，不表示产品提供历史浏览入口。
         *     如果调用方提供的预期版本已经被替换、回滚或下线，服务端返回当前安全版本，
         *     并在 `resolution` 中说明发生了版本变化。
         */
        get: operations["getDailyContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/daily/{fortuneDate}/looks/{lookId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取指定内容版本中的穿搭详情 */
        get: operations["getLookDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/poster-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 获取已有海报或创建海报渲染任务
         * @description 海报只使用已经发布的内容、已审核图片和已冻结模板，不调用 AI 生图。
         *     相同业务意图的网络重试必须复用同一个 `Idempotency-Key`。
         */
        post: operations["createPosterJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/poster-jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询海报任务状态 */
        get: operations["getPosterJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback-reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 提交内容纠错或产品建议 */
        post: operations["createFeedbackReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/auth/password-challenges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 校验单一维护者账号与密码并创建一次性 TOTP 挑战
         * @description 无论账号是否存在，失败时都执行等价密码哈希校验并返回同一错误。
         *     请求在解析正文前先接受持久化的请求来源级限流；严格解析并规范化账号后、
         *     执行昂贵密码哈希前，再接受持久化的账号级限流。
         *     虽然此阶段尚无会话 CSRF 令牌，请求仍必须携带并通过可信同源 `Origin` 校验。
         *     挑战只能使用一次，并在五分钟后失效。
         */
        post: operations["createAdminPasswordChallenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 使用密码挑战与 TOTP 动态码建立后台会话
         * @description 服务端在 PostgreSQL 中原子消费一次性密码挑战和 TOTP counter；允许的时钟偏差内，
         *     已用于登录或其他高风险动作的同一 counter 也不能再次使用。成功后只通过同源
         *     `HttpOnly`、`Secure`、`SameSite=Strict`、`Path=/admin` 且无 `Domain` 的 Cookie
         *     返回随机会话令牌，响应正文只返回与该会话绑定的 CSRF 令牌和会话期限。此请求在
         *     会话建立前没有 CSRF 令牌，但仍必须通过可信同源 `Origin` 校验。
         */
        post: operations["createAdminSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查看当前后台会话及 CSRF 令牌 */
        get: operations["getAdminSession"];
        put?: never;
        post?: never;
        /**
         * 安全退出当前后台会话
         * @description 必须同时通过可信同源 `Origin` 与会话绑定的 CSRF 令牌校验。
         */
        delete: operations["deleteAdminSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 原子注销单一维护者的全部后台会话
         * @description 必须同时通过可信同源 `Origin` 与会话绑定的 CSRF 令牌校验。成功后原子撤销
         *     全部现有会话并作废尚未消费的登录挑战，不能由操作前签发的挑战重新建立会话。
         */
        post: operations["logoutAllAdminSessions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/auth/recovery-challenges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 原子消费一个恢复码并开始两阶段控制权恢复
         * @description 正确恢复码在 PostgreSQL 中只消费一次，并立即提升凭据修订号、注销全部会话、
         *     使旧验证器和全部旧恢复码失效。随后只签发十分钟有效、一次性的恢复挑战，
         *     同时给出待启用的新 TOTP 配置。失败不暴露账号或恢复码是否存在；请求来源在正文解析前
         *     限流，账号在严格解析并规范化后、校验恢复码前限流。此未登录请求仍必须通过可信同源
         *     `Origin` 校验。
         */
        post: operations["createAdminRecoveryChallenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/auth/recovery-completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 完成新密码与新验证器设置并签发新的恢复码
         * @description 原子消费十分钟恢复挑战并校验待启用 TOTP 的未使用 counter。成功后启用新凭据，
         *     一次性返回恰好十个新恢复码并建立新会话；服务端只保存恢复码摘要。此请求在新会话
         *     建立前没有 CSRF 令牌，但仍必须通过可信同源 `Origin` 校验。
         */
        post: operations["completeAdminRecovery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/security-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询至少保留 365 天的关键登录与安全记录
         * @description 只返回单向来源指纹和受限浏览器摘要，不返回 IP、密码、动态码、恢复码、挑战或会话原文。
         */
        get: operations["listSecurityEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/emergency-control": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查看全局公开内容开关及其修订号 */
        get: operations["getEmergencyControlStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/emergency-control/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 紧急停止全部公开内容
         * @description 必须重新校验当前 TOTP、精确短语“停止全部公开内容”和原因，并原子消费 TOTP counter。
         *     成功后源站立即 fail closed；已经下载或被外部转发的副本无法召回，正式 CDN 的
         *     `purge/deny` 联动由 Issue #34 在真实部署环境验收。
         */
        post: operations["stopPublicAccess"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/emergency-control/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 恢复全部公开内容
         * @description 必须重新校验当前 TOTP、精确短语“恢复全部公开内容”和原因，并原子消费 TOTP counter。
         *     恢复只解除全局开关；每个内容版本仍须独立满足已发布、审核和素材安全条件。
         */
        post: operations["resumePublicAccess"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/daily-content-drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查看仍可继续编辑的草稿
         * @description 按更新时间倒序返回草稿；可选按命理日筛选，不依赖浏览器本地存储恢复工作。
         */
        get: operations["listDailyContentDrafts"];
        put?: never;
        /** 创建某个命理日的草稿 */
        post: operations["createDailyContentDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/daily-content-drafts/{draftId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查看草稿 */
        get: operations["getDailyContentDraft"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/daily-content-drafts/{draftId}/modules/{moduleCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 修改草稿中的一个内容模块
         * @description 只允许修改 `draft`。请求体必须与路径中的 `moduleCode` 对应。
         *     成功后服务端增加 `draftRevision` 并返回新的草稿 ETag。
         */
        patch: operations["updateDailyContentDraftModule"];
        trace?: never;
    };
    "/admin/api/v1/daily-content-drafts/{draftId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 冻结草稿并创建不可修改的内容版本 */
        post: operations["submitDailyContentDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/daily-content-versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查看某命理日的全部内容版本 */
        get: operations["listDailyContentVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/daily-content-versions/{contentVersion}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查看不可变内容、状态、检查和大师确认依据 */
        get: operations["getDailyContentVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/daily-content-versions/{contentVersion}/master-review-evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登记大师在系统外留下的确认依据 */
        post: operations["addMasterReviewEvidence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/daily-content-versions/{contentVersion}/review-decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 运行必审检查并批准或退回当前内容版本 */
        post: operations["decideDailyContentReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/daily-content-versions/{contentVersion}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 安排内容版本在指定时间上线 */
        post: operations["scheduleDailyContentVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/daily-content-versions/{contentVersion}/cancel-schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 取消未生效排期并回到 `approved` */
        post: operations["cancelDailyContentSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/daily-content-versions/{contentVersion}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 立即发布已批准的内容版本 */
        post: operations["publishDailyContentVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/daily-content-versions/{contentVersion}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 下线当前版本并可同时恢复安全旧版本 */
        post: operations["withdrawDailyContentVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/daily-content-days/{fortuneDate}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 恢复同一命理日曾经发布且仍安全的旧版本 */
        post: operations["rollbackDailyContentDay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询内容生命周期审计记录 */
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: date
         * @description Five 命理日；北京时间 23:00 进入下一命理日。
         * @example 2026-07-15
         */
        FortuneDate: string;
        /**
         * Format: date-time
         * @example 2026-07-14T23:30:00+08:00
         */
        ZonedDateTime: string;
        /**
         * @description 不透明内容版本；禁止首尾空白及 C0/DEL 控制字符，调用方只能比较相等，不得解析。
         * @example fd-20260715-r3
         */
        ContentVersion: string;
        /** @description 不透明标识；调用方不得解析。 */
        OpaqueId: string;
        NullableContentVersion: components["schemas"]["ContentVersion"] | null;
        /** @enum {string} */
        ElementCode: "wood" | "fire" | "earth" | "metal" | "water";
        /** @enum {string} */
        TierCode: "da_ji" | "ci_ji" | "ping" | "jiao_cha" | "bu_li";
        /** @enum {string} */
        ContentState: "draft" | "in_review" | "changes_requested" | "approved" | "scheduled" | "published" | "superseded" | "withdrawn";
        /** @enum {string} */
        ModuleCode: "calendar_algorithm" | "copy_and_formula" | "visual_and_rights" | "poster_consistency";
        /** @description 由离线 bootstrap 命令首次创建的唯一小写 ASCII 维护者账号名；限流与校验使用同一规范值。 */
        AdminUsername: string;
        /** @description 登录或恢复输入；服务端在限流与凭据校验前执行 NFKC、去除首尾空白并转为规范小写账号名。 */
        AdminUsernameInput: string;
        /** @description 以 Unicode code point 计 16 至 128 位；只从请求正文或交互式 stdin 接收，禁止进入 CLI 参数、环境变量或日志。 */
        AdminPassword: string;
        /** @description 当前验证器生成的六位动态码；服务端必须原子拒绝已经接受过的 counter。 */
        TotpCode: string;
        /** @description 256-bit 随机一次性挑战原文；服务端只持久化域分离 HMAC 摘要。 */
        AuthChallengeToken: string;
        /** @description 高强度一次性恢复码原文；服务端只持久化域分离 HMAC 摘要。 */
        RecoveryCode: string;
        CreatePasswordChallengeRequest: {
            username: components["schemas"]["AdminUsernameInput"];
            password: components["schemas"]["AdminPassword"];
        };
        PasswordChallenge: {
            challengeToken: components["schemas"]["AuthChallengeToken"];
            expiresAt: components["schemas"]["ZonedDateTime"];
        };
        CreateAdminSessionRequest: {
            challengeToken: components["schemas"]["AuthChallengeToken"];
            totpCode: components["schemas"]["TotpCode"];
        };
        AdminSession: {
            username: components["schemas"]["AdminUsername"];
            issuedAt: components["schemas"]["ZonedDateTime"];
            idleExpiresAt: components["schemas"]["ZonedDateTime"];
            absoluteExpiresAt: components["schemas"]["ZonedDateTime"];
            /** @description 会话绑定的随机令牌，只保存在运行中页面内存。 */
            csrfToken: string;
            credentialRevision: number;
        };
        CreateRecoveryChallengeRequest: {
            username: components["schemas"]["AdminUsernameInput"];
            recoveryCode: components["schemas"]["RecoveryCode"];
        };
        TotpProvisioning: {
            /** @description 待启用的 TOTP Base32 密钥，只在本次 no-store 恢复挑战响应中返回。 */
            secret: string;
            /**
             * Format: uri
             * @description 与 `secret` 相同的待启用配置，只用于验证器录入，禁止记录日志。
             */
            otpauthUri: string;
            /** @constant */
            algorithm: "SHA1";
            /** @constant */
            digits: 6;
            /** @constant */
            periodSeconds: 30;
        };
        RecoveryChallenge: {
            challengeToken: components["schemas"]["AuthChallengeToken"];
            expiresAt: components["schemas"]["ZonedDateTime"];
            totpProvisioning: components["schemas"]["TotpProvisioning"];
        };
        CompleteRecoveryRequest: {
            challengeToken: components["schemas"]["AuthChallengeToken"];
            newPassword: components["schemas"]["AdminPassword"];
            totpCode: components["schemas"]["TotpCode"];
        };
        RecoveryCompletion: {
            session: components["schemas"]["AdminSession"];
            /** @description 新的一套十个一次性恢复码；只在本次 no-store 响应显示。 */
            recoveryCodes: components["schemas"]["RecoveryCode"][];
        };
        /** @enum {string} */
        SecurityEventAction: "bootstrap_completed" | "login_password" | "login_totp" | "logout_current" | "logout_all" | "recovery_code" | "recovery_completed" | "offline_reset" | "csrf_rejected" | "rate_limited" | "emergency_stop" | "emergency_resume";
        /** @enum {string} */
        SecurityEventOutcome: "succeeded" | "rejected";
        SecurityEvent: {
            eventId: components["schemas"]["OpaqueId"];
            occurredAt: components["schemas"]["ZonedDateTime"];
            action: components["schemas"]["SecurityEventAction"];
            outcome: components["schemas"]["SecurityEventOutcome"];
            requestId: string;
            /** @description 使用部署密钥生成的单向来源指纹，不是 IP 或可逆地址。 */
            sourceFingerprint: string;
            /** @description 经过截断和字段白名单处理的浏览器摘要，不保存完整 User-Agent。 */
            clientSummary: string | null;
            /** @description 仅返回紧急控制或离线重置等动作明确记录的审计原因；认证凭据和内部异常不得写入此字段。 */
            reason: string | null;
        };
        SecurityEventPage: {
            items: components["schemas"]["SecurityEvent"][];
            nextCursor: string | null;
        };
        EmergencyControlStatus: {
            publicAccessEnabled: boolean;
            revision: number;
            changedAt: components["schemas"]["ZonedDateTime"];
            reason: string | null;
            auditEventId: components["schemas"]["OpaqueId"] | null;
        };
        EmergencyStopRequest: {
            totpCode: components["schemas"]["TotpCode"];
            /** @constant */
            confirmationPhrase: "停止全部公开内容";
            reason: string;
        };
        EmergencyResumeRequest: {
            totpCode: components["schemas"]["TotpCode"];
            /** @constant */
            confirmationPhrase: "恢复全部公开内容";
            reason: string;
        };
        RequestContext: {
            responseGeneratedAt: components["schemas"]["ZonedDateTime"];
            /** Format: date */
            civilDate: string;
            fortuneDate: components["schemas"]["FortuneDate"];
            /** @enum {string} */
            shichen: "子" | "丑" | "寅" | "卯" | "辰" | "巳" | "午" | "未" | "申" | "酉" | "戌" | "亥";
            /** @constant */
            timezone: "Asia/Shanghai";
            /** @constant */
            dayBoundary: "23:00";
            crossedDayBoundary: boolean;
        };
        CalendarInfo: {
            weekdayText: string;
            lunarDateText: string;
            ganzhiDay: string;
            /** @enum {string} */
            branch: "子" | "丑" | "寅" | "卯" | "辰" | "巳" | "午" | "未" | "申" | "酉" | "戌" | "亥";
            dayElement: components["schemas"]["ElementCode"];
            /** @enum {string} */
            dayElementLabel: "木" | "火" | "土" | "金" | "水";
        };
        ColorRef: {
            colorCode: string;
            name: string;
        };
        Tier: {
            rank: number;
            tierCode: components["schemas"]["TierCode"];
            /** @enum {string} */
            algorithmLabel: "大吉" | "次吉" | "平" | "较差" | "不利";
            /** @enum {string} */
            displayLabel: "今日优先" | "稳妥选择" | "日常可穿" | "注意";
            /**
             * @description 大吉、次吉、平为 `primary`；较差和不利为 `attention`。
             *     网页按此字段合并展示，不自行重算五行关系。
             * @enum {string}
             */
            displaySection: "primary" | "attention";
            element: components["schemas"]["ElementCode"];
            /** @enum {string} */
            elementLabel: "木" | "火" | "土" | "金" | "水";
            colors: components["schemas"]["ColorRef"][];
            relationText: string;
            explanation: string;
        };
        BalanceSuggestion: {
            /** @constant */
            title: "已经穿了注意色";
            /** @constant */
            description: "可以用当日大吉色的普通配饰做小面积补充，不需要整套换衣。";
            /** @constant */
            preferredTierCode: "da_ji";
            accessoryExamples: ("丝巾" | "围巾" | "包" | "鞋" | "领带" | "耳饰" | "手机壳" | "帽子" | "腰带" | "首饰")[];
        };
        Scenario: {
            code: string;
            label: string;
        };
        Audience: {
            code: string;
            label: string;
        };
        OutfitSlot: {
            /** @enum {string} */
            role: "primary" | "secondary" | "accent";
            /** @enum {string} */
            roleLabel: "主色" | "辅助色" | "点缀色";
            tierCode: components["schemas"]["TierCode"];
            colorCodes: string[];
            ratioPercent: number | null;
            garmentParts: string[];
        };
        OutfitFormula: {
            formulaId: components["schemas"]["OpaqueId"];
            /** @enum {string} */
            kind: "mono" | "dual" | "triple";
            title: string;
            scenario: components["schemas"]["Scenario"];
            audience: components["schemas"]["Audience"];
            slots: components["schemas"]["OutfitSlot"][];
            lookIds: components["schemas"]["OpaqueId"][];
            disclaimer: string;
        };
        PublicImageAsset: {
            assetId: components["schemas"]["OpaqueId"];
            /** Format: uri */
            url: string;
            width: number;
            height: number;
            /** @enum {string} */
            mediaType: "image/avif" | "image/webp" | "image/jpeg" | "image/png";
            altText: string;
            aiGenerated: boolean;
            aiDisclosure: string | null;
        };
        GarmentItem: {
            /** @enum {string} */
            category: "top" | "bottom" | "dress" | "outerwear" | "shoes" | "bag" | "accessory";
            categoryLabel: string;
            colorCode: string;
            description: string;
        };
        LookAlternative: {
            replaceCategory: string;
            description: string;
        };
        PublicLook: {
            lookId: components["schemas"]["OpaqueId"];
            formulaId: components["schemas"]["OpaqueId"];
            requiredForPublish: boolean;
            sortOrder: number;
            title: string;
            scenario: components["schemas"]["Scenario"];
            audience: components["schemas"]["Audience"];
            coverImage: components["schemas"]["PublicImageAsset"];
            detailImages: components["schemas"]["PublicImageAsset"][];
            items: components["schemas"]["GarmentItem"][];
            alternatives: components["schemas"]["LookAlternative"][];
        };
        Basis: {
            steps: string[];
            disclaimer: string;
        };
        ShareContent: {
            summaryText: string;
            copyText: string;
            posterTemplateVersion: string;
            /** @constant */
            posterJobEndpoint: "/api/v1/poster-jobs";
        };
        ContentVersionSet: {
            contentVersion: components["schemas"]["ContentVersion"];
            calendarDataVersion: string;
            calendarRuleVersion: string;
            algorithmVersion: string;
            copyVersion: string;
            outfitVersion: string;
            assetManifestVersion: string;
            posterTemplateVersion: string;
        };
        DailyContent: {
            fortuneDate: components["schemas"]["FortuneDate"];
            effectiveFrom: components["schemas"]["ZonedDateTime"];
            effectiveTo: components["schemas"]["ZonedDateTime"];
            calendar: components["schemas"]["CalendarInfo"];
            tiers: components["schemas"]["Tier"][];
            balanceSuggestion: components["schemas"]["BalanceSuggestion"];
            outfitFormulas: components["schemas"]["OutfitFormula"][];
            /** @description 恰好两项 `requiredForPublish=true`，第三项如果存在必须为可选。 */
            looks: components["schemas"]["PublicLook"][];
            basis: components["schemas"]["Basis"];
            share: components["schemas"]["ShareContent"];
            versions: components["schemas"]["ContentVersionSet"];
        };
        TodayResponse: {
            requestContext: components["schemas"]["RequestContext"];
            content: components["schemas"]["DailyContent"];
        };
        VersionResolution: {
            expectedContentVersion: components["schemas"]["NullableContentVersion"];
            servedContentVersion: components["schemas"]["ContentVersion"];
            versionChanged: boolean;
            /** @enum {string} */
            reason: "current" | "replaced" | "rolled_back" | "withdrawn";
        };
        DailyContentResponse: {
            requestedFortuneDate: components["schemas"]["FortuneDate"];
            content: components["schemas"]["DailyContent"];
            resolution: components["schemas"]["VersionResolution"];
        };
        LookDetailResponse: {
            fortuneDate: components["schemas"]["FortuneDate"];
            contentVersion: components["schemas"]["ContentVersion"];
            look: components["schemas"]["PublicLook"];
        };
        CreatePosterJobRequest: {
            fortuneDate: components["schemas"]["FortuneDate"];
            expectedContentVersion: components["schemas"]["ContentVersion"];
            channelId: string;
        };
        PosterEntry: {
            /** @constant */
            type: "web_qr";
            /** Format: uri */
            landingUrl: string;
        };
        PosterJob: {
            jobId: components["schemas"]["OpaqueId"];
            /** @enum {string} */
            status: "processing" | "ready" | "failed" | "version_changed";
            sourceContentVersion: components["schemas"]["ContentVersion"];
            currentActiveContentVersion: components["schemas"]["NullableContentVersion"];
            posterTemplateVersion: string;
            posterInstanceId: components["schemas"]["OpaqueId"] | null;
            channelId: string;
            assetUrl: string | null;
            entry: components["schemas"]["PosterEntry"] | null;
        };
        CreateFeedbackRequest: {
            /** @enum {string} */
            category: "content_error" | "product_feedback";
            /** @description 至少包含一个非空白字符；允许制表符和换行，拒绝其他 C0 与全部 C1 控制字符。 */
            message: string;
            fortuneDate: components["schemas"]["FortuneDate"];
            contentVersion: components["schemas"]["ContentVersion"];
            /** @description 不透明渠道标识；禁止首尾空白及 C0/DEL 控制字符。 */
            channelId: string;
            /** @description 只有用户单独同意后才可填写。 */
            contact: string | null;
        };
        CreateFeedbackResponse: {
            feedbackId: components["schemas"]["OpaqueId"];
            /** @constant */
            status: "received";
        };
        DraftRevision: number;
        LifecycleRevision: number;
        CalendarAlgorithmModule: {
            calendar: components["schemas"]["CalendarInfo"];
            tiers: components["schemas"]["Tier"][];
            calendarDataVersion: string;
            calendarRuleVersion: string;
            algorithmVersion: string;
        };
        CopyAndFormulaModule: {
            balanceSuggestion: components["schemas"]["BalanceSuggestion"];
            outfitFormulas: components["schemas"]["OutfitFormula"][];
            basis: components["schemas"]["Basis"];
            share: components["schemas"]["ShareContent"];
            copyVersion: string;
            outfitVersion: string;
        };
        /** @enum {string} */
        ImageRightsStatus: "pending" | "cleared" | "rejected" | "revoked";
        /** @enum {string} */
        ImageReviewStatus: "pending" | "approved" | "rejected" | "withdrawn";
        /** @enum {string} */
        AiLabelStatus: "not_applicable" | "pending" | "complete" | "failed";
        AdminImageAsset: {
            assetId: components["schemas"]["OpaqueId"];
            /** @description 上传完成前可为空；公开响应只返回已经审核通过的不可变 URL。 */
            fileUrl: string | null;
            width: number;
            height: number;
            /** @enum {string} */
            mediaType: "image/avif" | "image/webp" | "image/jpeg" | "image/png";
            altText: string;
            sha256: string;
            /** @enum {string} */
            sourceType: "licensed" | "ai_generated" | "fallback_template";
            declaredModel: string | null;
            promptVersion: string | null;
            generatedAt: components["schemas"]["ZonedDateTime"] | null;
            reviewStatus: components["schemas"]["ImageReviewStatus"];
            rightsStatus: components["schemas"]["ImageRightsStatus"];
            aiLabelStatus: components["schemas"]["AiLabelStatus"];
            rightsRecordIds: components["schemas"]["OpaqueId"][];
        };
        LookDraft: {
            lookId: components["schemas"]["OpaqueId"];
            formulaId: components["schemas"]["OpaqueId"];
            requiredForPublish: boolean;
            sortOrder: number;
            title: string;
            scenario: components["schemas"]["Scenario"];
            audience: components["schemas"]["Audience"];
            coverAssetId: components["schemas"]["OpaqueId"];
            detailAssetIds: components["schemas"]["OpaqueId"][];
            items: components["schemas"]["GarmentItem"][];
            alternatives: components["schemas"]["LookAlternative"][];
        };
        RightsRecord: {
            rightsRecordId: components["schemas"]["OpaqueId"];
            /** @enum {string} */
            kind: "license" | "terms_snapshot" | "purchase_receipt" | "consent" | "internal_record";
            reference: string;
            recordedAt: components["schemas"]["ZonedDateTime"];
        };
        VisualAndRightsModule: {
            looks: components["schemas"]["LookDraft"][];
            assets: components["schemas"]["AdminImageAsset"][];
            rightsRecords: components["schemas"]["RightsRecord"][];
            assetManifestVersion: string;
        };
        PosterConsistencyModule: {
            posterTemplateVersion: string;
            templateId: components["schemas"]["OpaqueId"];
            sampleAssetId: components["schemas"]["OpaqueId"];
        };
        DraftModules: {
            calendar_algorithm: components["schemas"]["CalendarAlgorithmModule"] | null;
            copy_and_formula: components["schemas"]["CopyAndFormulaModule"] | null;
            visual_and_rights: components["schemas"]["VisualAndRightsModule"] | null;
            poster_consistency: components["schemas"]["PosterConsistencyModule"] | null;
        };
        ContentDraft: {
            draftId: components["schemas"]["OpaqueId"];
            fortuneDate: components["schemas"]["FortuneDate"];
            /** @constant */
            state: "draft";
            draftRevision: components["schemas"]["DraftRevision"];
            modules: components["schemas"]["DraftModules"];
            createdAt: components["schemas"]["ZonedDateTime"];
            updatedAt: components["schemas"]["ZonedDateTime"];
        };
        ContentDraftSummary: {
            draftId: components["schemas"]["OpaqueId"];
            fortuneDate: components["schemas"]["FortuneDate"];
            /** @constant */
            state: "draft";
            draftRevision: components["schemas"]["DraftRevision"];
            createdAt: components["schemas"]["ZonedDateTime"];
            updatedAt: components["schemas"]["ZonedDateTime"];
        };
        ContentDraftList: {
            items: components["schemas"]["ContentDraftSummary"][];
        };
        CreateDraftRequest: {
            fortuneDate: components["schemas"]["FortuneDate"];
            copyFromContentVersion: components["schemas"]["NullableContentVersion"];
        };
        DraftModuleUpdate: components["schemas"]["CalendarAlgorithmModule"] | components["schemas"]["CopyAndFormulaModule"] | components["schemas"]["VisualAndRightsModule"] | components["schemas"]["PosterConsistencyModule"];
        UpdatedDraftModule: {
            draftId: components["schemas"]["OpaqueId"];
            moduleCode: components["schemas"]["ModuleCode"];
            draftRevision: components["schemas"]["DraftRevision"];
            module: components["schemas"]["DraftModuleUpdate"];
        };
        SubmitDraftResult: {
            draftId: components["schemas"]["OpaqueId"];
            contentVersion: components["schemas"]["ContentVersion"];
            /** @constant */
            state: "in_review";
            lifecycleRevision: components["schemas"]["LifecycleRevision"];
        };
        PreflightCheck: {
            /** @enum {string} */
            code: "calendar_algorithm" | "calendar_golden_data" | "master_review_evidence" | "copy_and_formula" | "required_images" | "visual_and_rights" | "ai_label" | "poster_consistency" | "reference_integrity";
            /** @enum {string} */
            status: "pending" | "passed" | "failed";
            message: string;
        };
        EvidenceReference: {
            /** @enum {string} */
            kind: "attachment" | "message_link" | "document" | "note";
            reference: string;
        };
        MasterReviewEvidence: {
            evidenceId: components["schemas"]["OpaqueId"];
            reviewerDisplayName: string;
            reviewedAt: components["schemas"]["ZonedDateTime"];
            /** @enum {string} */
            conclusion: "confirmed" | "changes_requested";
            notes: string;
            references: components["schemas"]["EvidenceReference"][];
        };
        AddMasterReviewEvidenceRequest: {
            reviewerDisplayName: string;
            reviewedAt: components["schemas"]["ZonedDateTime"];
            /** @enum {string} */
            conclusion: "confirmed" | "changes_requested";
            notes: string;
            references: components["schemas"]["EvidenceReference"][];
        };
        ContentVersionSummary: {
            contentVersion: components["schemas"]["ContentVersion"];
            state: components["schemas"]["ContentState"];
            lifecycleRevision: components["schemas"]["LifecycleRevision"];
            createdAt: components["schemas"]["ZonedDateTime"];
            effectiveFrom: components["schemas"]["ZonedDateTime"] | null;
            effectiveTo: components["schemas"]["ZonedDateTime"] | null;
        };
        AdminContentVersion: {
            contentVersion: components["schemas"]["ContentVersion"];
            fortuneDate: components["schemas"]["FortuneDate"];
            state: components["schemas"]["ContentState"];
            lifecycleRevision: components["schemas"]["LifecycleRevision"];
            activeContentVersion: components["schemas"]["NullableContentVersion"];
            snapshot: components["schemas"]["DraftModules"];
            preflightChecks: components["schemas"]["PreflightCheck"][];
            masterReviewEvidence: components["schemas"]["MasterReviewEvidence"][];
        };
        ReviewDecisionRequest: {
            /** @enum {string} */
            decision: "approved" | "changes_requested";
            /** @description `changes_requested` 时必须填写。 */
            reason: string | null;
        };
        ExpectedActiveVersionRequest: {
            expectedActiveContentVersion: components["schemas"]["NullableContentVersion"];
            reason: string;
        };
        ScheduleRequest: {
            expectedActiveContentVersion: components["schemas"]["NullableContentVersion"];
            reason: string;
            effectiveFrom: components["schemas"]["ZonedDateTime"];
        };
        WithdrawRequest: {
            expectedActiveContentVersion: components["schemas"]["NullableContentVersion"];
            reason: string;
            replacementContentVersion: components["schemas"]["NullableContentVersion"];
        };
        RollbackRequest: {
            expectedActiveContentVersion: components["schemas"]["NullableContentVersion"];
            reason: string;
            targetContentVersion: components["schemas"]["ContentVersion"];
        };
        StateTransition: {
            contentVersion: components["schemas"]["ContentVersion"];
            fromState: components["schemas"]["ContentState"];
            toState: components["schemas"]["ContentState"];
        };
        LifecycleActionResult: {
            fortuneDate: components["schemas"]["FortuneDate"];
            contentVersion: components["schemas"]["ContentVersion"];
            state: components["schemas"]["ContentState"];
            lifecycleRevision: components["schemas"]["LifecycleRevision"];
            activeContentVersion: components["schemas"]["NullableContentVersion"];
            transitions: components["schemas"]["StateTransition"][];
            auditEventId: components["schemas"]["OpaqueId"];
        };
        AuditEvent: {
            auditEventId: components["schemas"]["OpaqueId"];
            action: string;
            occurredAt: components["schemas"]["ZonedDateTime"];
            requestId: string;
            fortuneDate: components["schemas"]["FortuneDate"];
            contentVersion: components["schemas"]["ContentVersion"];
            reason: string;
        };
        AuditEventPage: {
            items: components["schemas"]["AuditEvent"][];
            nextCursor: string | null;
        };
        /** @enum {string} */
        ErrorCode: "INVALID_ARGUMENT" | "INVALID_FORTUNE_DATE" | "AUTHENTICATION_FAILED" | "AUTH_CHALLENGE_EXPIRED" | "RECOVERY_CHALLENGE_EXPIRED" | "UNAUTHENTICATED" | "FORBIDDEN" | "CSRF_VALIDATION_FAILED" | "RESOURCE_NOT_FOUND" | "CONTENT_NOT_FOUND" | "LOOK_NOT_FOUND" | "CONTENT_VERSION_CHANGED" | "ACTIVE_CONTENT_VERSION_CHANGED" | "IDEMPOTENCY_KEY_REUSED" | "TOTP_REPLAYED" | "EMERGENCY_CONTROL_CONFLICT" | "INVALID_STATE_TRANSITION" | "VERSION_WITHDRAWN" | "HISTORICAL_CONTENT_EXPIRED" | "REVISION_MISMATCH" | "REQUIRED_REVIEW_MISSING" | "MASTER_REVIEW_EVIDENCE_MISSING" | "PUBLISH_PRECHECK_FAILED" | "SCHEDULE_TIME_INVALID" | "PRECONDITION_REQUIRED" | "RATE_LIMITED" | "CONTENT_NOT_READY" | "PUBLIC_ACCESS_STOPPED" | "POSTER_GENERATION_UNAVAILABLE" | "FEEDBACK_UNAVAILABLE" | "ADMIN_SERVICE_UNAVAILABLE";
        Error: {
            code: components["schemas"]["ErrorCode"];
            message: string;
            retryable: boolean;
            requestId: string;
            details: {
                [key: string]: unknown;
            };
        };
        ErrorEnvelope: {
            error: components["schemas"]["Error"];
        };
    };
    responses: {
        /** @description 请求字段或格式无效 */
        InvalidArgument: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 认证、恢复或高风险确认请求字段无效 */
        AuthInvalidArgument: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                "Cache-Control": components["headers"]["NoStoreCacheControl"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /**
         * @description 凭据、一次性挑战或动态码无效。账号不存在、密码错误、恢复码错误和未认证阶段的
         *     TOTP 重放必须使用相同状态和对外文案，不能帮助枚举账号或凭据。
         */
        AuthenticationFailed: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                "Cache-Control": components["headers"]["NoStoreCacheControl"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 后台会话不存在或已失效，或者高风险操作要求的当前 TOTP 无效 */
        AdminReauthenticationFailed: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                "Cache-Control": components["headers"]["NoStoreCacheControl"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 命理日格式或允许范围无效 */
        InvalidFortuneDate: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 后台会话不存在或已失效 */
        Unauthenticated: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                "Cache-Control": components["headers"]["NoStoreCacheControl"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 后台凭据库或安全控制服务暂时不可用；调用方应保留当前输入并稍后重试 */
        AdminServiceUnavailable: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                "Retry-After"?: number;
                "Cache-Control": components["headers"]["NoStoreCacheControl"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 后台写请求的可信同源 `Origin` 或会话绑定 CSRF 令牌校验失败 */
        CsrfValidationFailed: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                "Cache-Control": components["headers"]["NoStoreCacheControl"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description TOTP counter 重放、幂等键复用或紧急控制状态发生冲突 */
        AuthConflict: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                "Cache-Control": components["headers"]["NoStoreCacheControl"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 幂等键、活跃版本或状态发生冲突 */
        Conflict: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 指定命理日没有可公开内容 */
        ContentNotFound: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 搭配不存在于当前内容版本 */
        LookNotFound: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 后台资源或任务不存在 */
        ResourceNotFound: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 网页持有的内容版本不是当前活跃版本 */
        ContentVersionChanged: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                "X-Content-Version": components["headers"]["XContentVersion"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 当前状态不允许执行该动作 */
        InvalidStateTransition: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 指定日期的公开内容超过保留期 */
        HistoricalContentExpired: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description `If-Match` 不是资源当前修订号 */
        RevisionMismatch: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                /** @description 当前资源 ETag，调用方必须刷新后再操作。 */
                ETag?: string;
                "Cache-Control": components["headers"]["NoStoreCacheControl"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 大师依据或必审检查不完整 */
        ReviewMissing: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 发布、排期或恢复检查未通过 */
        PublishPrecheckFailed: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 需要并发保护的写操作缺少 `If-Match` */
        PreconditionRequired: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                "Cache-Control": components["headers"]["NoStoreCacheControl"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 请求过于频繁 */
        RateLimited: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 登录或恢复请求触发持久化的请求来源级或账号级限流 */
        AuthRateLimited: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                "Retry-After"?: number;
                "Cache-Control": components["headers"]["NoStoreCacheControl"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /**
         * @description 当前日期没有可公开内容（`CONTENT_NOT_READY`），或全局紧急开关已经关闭公开读取
         *     （`PUBLIC_ACCESS_STOPPED`）。两种情况都必须 fail closed，不能返回旧缓存或临时计算结果。
         */
        PublicContentUnavailable: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /**
         * @description 海报服务暂时不可用（`POSTER_GENERATION_UNAVAILABLE`），或全局紧急开关已经关闭海报创建、
         *     查询与源站素材读取（`PUBLIC_ACCESS_STOPPED`）。只有前一种情况不影响基础每日内容。
         */
        PosterUnavailable: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 反馈暂时无法接收，公共内容不受影响 */
        FeedbackUnavailable: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 全局公开内容开关已在 PostgreSQL 事务中更新并追加安全审计 */
        EmergencyControlSucceeded: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                "Cache-Control": components["headers"]["NoStoreCacheControl"];
                ETag: components["headers"]["EmergencyControlETag"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["EmergencyControlStatus"];
            };
        };
        /** @description 状态变化已在一个事务中完成 */
        LifecycleActionSucceeded: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                "Cache-Control": components["headers"]["NoStoreCacheControl"];
                ETag: components["headers"]["LifecycleETag"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["LifecycleActionResult"];
            };
        };
    };
    parameters: {
        FortuneDate: components["schemas"]["FortuneDate"];
        FortuneDateQuery: components["schemas"]["FortuneDate"];
        FortuneDateQueryOptional: components["schemas"]["FortuneDate"];
        LookId: components["schemas"]["OpaqueId"];
        JobId: components["schemas"]["OpaqueId"];
        DraftId: components["schemas"]["OpaqueId"];
        ContentVersionPath: components["schemas"]["ContentVersion"];
        ModuleCode: components["schemas"]["ModuleCode"];
        ExpectedContentVersionOptional: components["schemas"]["ContentVersion"];
        ExpectedContentVersionRequired: components["schemas"]["ContentVersion"];
        /**
         * @description 草稿写操作使用响应中的草稿 ETag；生命周期写操作使用内容版本 ETag；
         *     全局紧急控制使用公开内容开关 ETag。调用方必须原样回传，不能自行拼接。
         */
        IfMatch: string;
        /** @description 同一业务意图的网络重试必须复用同一个高熵不透明值。 */
        IdempotencyKey: string;
        /**
         * @description 当前后台会话绑定的随机 CSRF 令牌。后台写操作还必须由服务端校验可信同源 `Origin`；
         *     令牌只能保存在运行中页面内存，不能放入 localStorage、URL 或日志。
         */
        XCsrfToken: string;
    };
    requestBodies: never;
    headers: {
        /** @description 当前外部请求的追踪编号；缓存命中时也必须按请求生成。 */
        XRequestId: string;
        /** @description 当前响应中的业务内容版本。 */
        XContentVersion: components["schemas"]["ContentVersion"];
        /** @description 完整 HTTP 响应表示的校验值，与 `contentVersion` 不是同一概念。 */
        RepresentationETag: string;
        /** @description 草稿当前修订号的强 ETag，例如 `"draft:7"`。 */
        DraftETag: string;
        /** @description 内容生命周期当前修订号的强 ETag，例如 `"lifecycle:12"`。 */
        LifecycleETag: string;
        /** @description 全局公开内容开关当前修订号的强 ETag，例如 `"emergency-control:4"`。 */
        EmergencyControlETag: string;
        /** @description 认证、恢复、安全记录和紧急控制响应不得被浏览器或中间层保存。 */
        NoStoreCacheControl: "no-store";
        /**
         * @description 只包含随机会话令牌；生产环境固定使用 `HttpOnly; Secure; SameSite=Strict; Path=/admin`，
         *     不设置 `Domain`，闲置 30 分钟失效且绝对有效期不超过 12 小时。
         */
        AdminSessionSetCookie: string;
        /** @description 以相同 Cookie 属性和立即过期时间清除 `five_admin_session`。 */
        AdminSessionClearedCookie: string;
        /**
         * @description `public, max-age=0, s-maxage=N, must-revalidate`。
         *     N 是 60 秒、内容结束、下一时辰和下一民用午夜剩余秒数中的最小值。
         */
        DynamicCacheControl: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getToday: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前命理日存在可以公开读取的内容 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    "X-Content-Version": components["headers"]["XContentVersion"];
                    ETag: components["headers"]["RepresentationETag"];
                    "Cache-Control": components["headers"]["DynamicCacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayResponse"];
                };
            };
            /** @description `If-None-Match` 对应的完整响应表示仍有效 */
            304: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    ETag: components["headers"]["RepresentationETag"];
                    "Cache-Control": components["headers"]["DynamicCacheControl"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["RateLimited"];
            503: components["responses"]["PublicContentUnavailable"];
        };
    };
    getDailyContent: {
        parameters: {
            query?: {
                expectedContentVersion?: components["parameters"]["ExpectedContentVersionOptional"];
            };
            header?: never;
            path: {
                fortuneDate: components["parameters"]["FortuneDate"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 返回指定日期当前安全的公开内容 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    "X-Content-Version": components["headers"]["XContentVersion"];
                    ETag: components["headers"]["RepresentationETag"];
                    "Cache-Control": components["headers"]["DynamicCacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyContentResponse"];
                };
            };
            400: components["responses"]["InvalidFortuneDate"];
            404: components["responses"]["ContentNotFound"];
            410: components["responses"]["HistoricalContentExpired"];
            503: components["responses"]["PublicContentUnavailable"];
        };
    };
    getLookDetail: {
        parameters: {
            query: {
                expectedContentVersion: components["parameters"]["ExpectedContentVersionRequired"];
            };
            header?: never;
            path: {
                fortuneDate: components["parameters"]["FortuneDate"];
                lookId: components["parameters"]["LookId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 返回与预期内容版本一致的穿搭详情 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    "X-Content-Version": components["headers"]["XContentVersion"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LookDetailResponse"];
                };
            };
            400: components["responses"]["InvalidFortuneDate"];
            404: components["responses"]["LookNotFound"];
            409: components["responses"]["ContentVersionChanged"];
            503: components["responses"]["PublicContentUnavailable"];
        };
    };
    createPosterJob: {
        parameters: {
            query?: never;
            header: {
                /** @description 同一业务意图的网络重试必须复用同一个高熵不透明值。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePosterJobRequest"];
            };
        };
        responses: {
            /** @description 已有相同海报实例 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PosterJob"];
                };
            };
            /** @description 已接受新的渲染任务 */
            202: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PosterJob"];
                };
            };
            /** @description 内容版本已变化或幂等键被用于另一请求 */
            409: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
            503: components["responses"]["PosterUnavailable"];
        };
    };
    getPosterJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 返回当前任务状态 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PosterJob"];
                };
            };
            404: components["responses"]["ResourceNotFound"];
            503: components["responses"]["PosterUnavailable"];
        };
    };
    createFeedbackReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFeedbackRequest"];
            };
        };
        responses: {
            /** @description 已接收反馈 */
            202: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateFeedbackResponse"];
                };
            };
            400: components["responses"]["InvalidArgument"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["FeedbackUnavailable"];
        };
    };
    createAdminPasswordChallenge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePasswordChallengeRequest"];
            };
        };
        responses: {
            /** @description 密码已校验，等待验证器动态码 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    "Cache-Control": components["headers"]["NoStoreCacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordChallenge"];
                };
            };
            400: components["responses"]["AuthInvalidArgument"];
            401: components["responses"]["AuthenticationFailed"];
            403: components["responses"]["CsrfValidationFailed"];
            429: components["responses"]["AuthRateLimited"];
            503: components["responses"]["AdminServiceUnavailable"];
        };
    };
    createAdminSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAdminSessionRequest"];
            };
        };
        responses: {
            /** @description 已建立 30 分钟闲置、12 小时绝对上限的后台会话 */
            201: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    "Cache-Control": components["headers"]["NoStoreCacheControl"];
                    "Set-Cookie": components["headers"]["AdminSessionSetCookie"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSession"];
                };
            };
            400: components["responses"]["AuthInvalidArgument"];
            401: components["responses"]["AuthenticationFailed"];
            403: components["responses"]["CsrfValidationFailed"];
            429: components["responses"]["AuthRateLimited"];
            503: components["responses"]["AdminServiceUnavailable"];
        };
    };
    getAdminSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前会话有效；访问会刷新闲置期限，但不能延长绝对期限 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    "Cache-Control": components["headers"]["NoStoreCacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSession"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            503: components["responses"]["AdminServiceUnavailable"];
        };
    };
    deleteAdminSession: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 当前后台会话绑定的随机 CSRF 令牌。后台写操作还必须由服务端校验可信同源 `Origin`；
                 *     令牌只能保存在运行中页面内存，不能放入 localStorage、URL 或日志。
                 */
                "X-CSRF-Token": components["parameters"]["XCsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前会话已注销；响应同时清除浏览器 Cookie */
            204: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    "Cache-Control": components["headers"]["NoStoreCacheControl"];
                    "Set-Cookie": components["headers"]["AdminSessionClearedCookie"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfValidationFailed"];
            503: components["responses"]["AdminServiceUnavailable"];
        };
    };
    logoutAllAdminSessions: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 当前后台会话绑定的随机 CSRF 令牌。后台写操作还必须由服务端校验可信同源 `Origin`；
                 *     令牌只能保存在运行中页面内存，不能放入 localStorage、URL 或日志。
                 */
                "X-CSRF-Token": components["parameters"]["XCsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 全部会话已注销；当前浏览器 Cookie 同时清除 */
            204: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    "Cache-Control": components["headers"]["NoStoreCacheControl"];
                    "Set-Cookie": components["headers"]["AdminSessionClearedCookie"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfValidationFailed"];
            503: components["responses"]["AdminServiceUnavailable"];
        };
    };
    createAdminRecoveryChallenge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRecoveryChallengeRequest"];
            };
        };
        responses: {
            /** @description 恢复码已消费，等待设置新密码并验证新的 TOTP */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    "Cache-Control": components["headers"]["NoStoreCacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryChallenge"];
                };
            };
            400: components["responses"]["AuthInvalidArgument"];
            401: components["responses"]["AuthenticationFailed"];
            403: components["responses"]["CsrfValidationFailed"];
            429: components["responses"]["AuthRateLimited"];
            503: components["responses"]["AdminServiceUnavailable"];
        };
    };
    completeAdminRecovery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteRecoveryRequest"];
            };
        };
        responses: {
            /** @description 已恢复控制权；新的恢复码只在本响应显示一次 */
            201: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    "Cache-Control": components["headers"]["NoStoreCacheControl"];
                    "Set-Cookie": components["headers"]["AdminSessionSetCookie"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryCompletion"];
                };
            };
            400: components["responses"]["AuthInvalidArgument"];
            401: components["responses"]["AuthenticationFailed"];
            403: components["responses"]["CsrfValidationFailed"];
            409: components["responses"]["AuthConflict"];
            429: components["responses"]["AuthRateLimited"];
            503: components["responses"]["AdminServiceUnavailable"];
        };
    };
    listSecurityEvents: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 按发生时间倒序返回安全记录 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    "Cache-Control": components["headers"]["NoStoreCacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecurityEventPage"];
                };
            };
            400: components["responses"]["AuthInvalidArgument"];
            401: components["responses"]["Unauthenticated"];
            503: components["responses"]["AdminServiceUnavailable"];
        };
    };
    getEmergencyControlStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 返回当前公开状态 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    "Cache-Control": components["headers"]["NoStoreCacheControl"];
                    ETag: components["headers"]["EmergencyControlETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmergencyControlStatus"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            503: components["responses"]["AdminServiceUnavailable"];
        };
    };
    stopPublicAccess: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 当前后台会话绑定的随机 CSRF 令牌。后台写操作还必须由服务端校验可信同源 `Origin`；
                 *     令牌只能保存在运行中页面内存，不能放入 localStorage、URL 或日志。
                 */
                "X-CSRF-Token": components["parameters"]["XCsrfToken"];
                /**
                 * @description 草稿写操作使用响应中的草稿 ETag；生命周期写操作使用内容版本 ETag；
                 *     全局紧急控制使用公开内容开关 ETag。调用方必须原样回传，不能自行拼接。
                 */
                "If-Match": components["parameters"]["IfMatch"];
                /** @description 同一业务意图的网络重试必须复用同一个高熵不透明值。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmergencyStopRequest"];
            };
        };
        responses: {
            200: components["responses"]["EmergencyControlSucceeded"];
            400: components["responses"]["AuthInvalidArgument"];
            401: components["responses"]["AdminReauthenticationFailed"];
            403: components["responses"]["CsrfValidationFailed"];
            409: components["responses"]["AuthConflict"];
            412: components["responses"]["RevisionMismatch"];
            428: components["responses"]["PreconditionRequired"];
            503: components["responses"]["AdminServiceUnavailable"];
        };
    };
    resumePublicAccess: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 当前后台会话绑定的随机 CSRF 令牌。后台写操作还必须由服务端校验可信同源 `Origin`；
                 *     令牌只能保存在运行中页面内存，不能放入 localStorage、URL 或日志。
                 */
                "X-CSRF-Token": components["parameters"]["XCsrfToken"];
                /**
                 * @description 草稿写操作使用响应中的草稿 ETag；生命周期写操作使用内容版本 ETag；
                 *     全局紧急控制使用公开内容开关 ETag。调用方必须原样回传，不能自行拼接。
                 */
                "If-Match": components["parameters"]["IfMatch"];
                /** @description 同一业务意图的网络重试必须复用同一个高熵不透明值。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmergencyResumeRequest"];
            };
        };
        responses: {
            200: components["responses"]["EmergencyControlSucceeded"];
            400: components["responses"]["AuthInvalidArgument"];
            401: components["responses"]["AdminReauthenticationFailed"];
            403: components["responses"]["CsrfValidationFailed"];
            409: components["responses"]["AuthConflict"];
            412: components["responses"]["RevisionMismatch"];
            428: components["responses"]["PreconditionRequired"];
            503: components["responses"]["AdminServiceUnavailable"];
        };
    };
    listDailyContentDrafts: {
        parameters: {
            query?: {
                fortuneDate?: components["parameters"]["FortuneDateQueryOptional"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 返回可继续编辑的草稿摘要 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    "Cache-Control": components["headers"]["NoStoreCacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentDraftList"];
                };
            };
            400: components["responses"]["InvalidFortuneDate"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    createDailyContentDraft: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 当前后台会话绑定的随机 CSRF 令牌。后台写操作还必须由服务端校验可信同源 `Origin`；
                 *     令牌只能保存在运行中页面内存，不能放入 localStorage、URL 或日志。
                 */
                "X-CSRF-Token": components["parameters"]["XCsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDraftRequest"];
            };
        };
        responses: {
            /** @description 已创建草稿 */
            201: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    "Cache-Control": components["headers"]["NoStoreCacheControl"];
                    ETag: components["headers"]["DraftETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentDraft"];
                };
            };
            400: components["responses"]["InvalidArgument"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfValidationFailed"];
            404: components["responses"]["ResourceNotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getDailyContentDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draftId: components["parameters"]["DraftId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 返回草稿及当前修订号 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    "Cache-Control": components["headers"]["NoStoreCacheControl"];
                    ETag: components["headers"]["DraftETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentDraft"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["ResourceNotFound"];
        };
    };
    updateDailyContentDraftModule: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 草稿写操作使用响应中的草稿 ETag；生命周期写操作使用内容版本 ETag；
                 *     全局紧急控制使用公开内容开关 ETag。调用方必须原样回传，不能自行拼接。
                 */
                "If-Match": components["parameters"]["IfMatch"];
                /**
                 * @description 当前后台会话绑定的随机 CSRF 令牌。后台写操作还必须由服务端校验可信同源 `Origin`；
                 *     令牌只能保存在运行中页面内存，不能放入 localStorage、URL 或日志。
                 */
                "X-CSRF-Token": components["parameters"]["XCsrfToken"];
            };
            path: {
                draftId: components["parameters"]["DraftId"];
                moduleCode: components["parameters"]["ModuleCode"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftModuleUpdate"];
            };
        };
        responses: {
            /** @description 返回更新后的模块和草稿修订号 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    "Cache-Control": components["headers"]["NoStoreCacheControl"];
                    ETag: components["headers"]["DraftETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdatedDraftModule"];
                };
            };
            400: components["responses"]["InvalidArgument"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfValidationFailed"];
            404: components["responses"]["ResourceNotFound"];
            409: components["responses"]["InvalidStateTransition"];
            412: components["responses"]["RevisionMismatch"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    submitDailyContentDraft: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 草稿写操作使用响应中的草稿 ETag；生命周期写操作使用内容版本 ETag；
                 *     全局紧急控制使用公开内容开关 ETag。调用方必须原样回传，不能自行拼接。
                 */
                "If-Match": components["parameters"]["IfMatch"];
                /** @description 同一业务意图的网络重试必须复用同一个高熵不透明值。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /**
                 * @description 当前后台会话绑定的随机 CSRF 令牌。后台写操作还必须由服务端校验可信同源 `Origin`；
                 *     令牌只能保存在运行中页面内存，不能放入 localStorage、URL 或日志。
                 */
                "X-CSRF-Token": components["parameters"]["XCsrfToken"];
            };
            path: {
                draftId: components["parameters"]["DraftId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已创建 `in_review` 内容版本 */
            201: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    "Cache-Control": components["headers"]["NoStoreCacheControl"];
                    ETag: components["headers"]["LifecycleETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitDraftResult"];
                };
            };
            400: components["responses"]["InvalidArgument"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfValidationFailed"];
            404: components["responses"]["ResourceNotFound"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["RevisionMismatch"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    listDailyContentVersions: {
        parameters: {
            query: {
                fortuneDate: components["parameters"]["FortuneDateQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 按创建时间倒序返回版本 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    "Cache-Control": components["headers"]["NoStoreCacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        fortuneDate: components["schemas"]["FortuneDate"];
                        activeContentVersion: components["schemas"]["ContentVersion"] | null;
                        items: components["schemas"]["ContentVersionSummary"][];
                    };
                };
            };
            400: components["responses"]["InvalidFortuneDate"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    getDailyContentVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contentVersion: components["parameters"]["ContentVersionPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 返回一个完整内容版本 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    "Cache-Control": components["headers"]["NoStoreCacheControl"];
                    ETag: components["headers"]["LifecycleETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminContentVersion"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["ResourceNotFound"];
        };
    };
    addMasterReviewEvidence: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 草稿写操作使用响应中的草稿 ETag；生命周期写操作使用内容版本 ETag；
                 *     全局紧急控制使用公开内容开关 ETag。调用方必须原样回传，不能自行拼接。
                 */
                "If-Match": components["parameters"]["IfMatch"];
                /** @description 同一业务意图的网络重试必须复用同一个高熵不透明值。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /**
                 * @description 当前后台会话绑定的随机 CSRF 令牌。后台写操作还必须由服务端校验可信同源 `Origin`；
                 *     令牌只能保存在运行中页面内存，不能放入 localStorage、URL 或日志。
                 */
                "X-CSRF-Token": components["parameters"]["XCsrfToken"];
            };
            path: {
                contentVersion: components["parameters"]["ContentVersionPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMasterReviewEvidenceRequest"];
            };
        };
        responses: {
            /** @description 已登记依据并增加生命周期修订号 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    "Cache-Control": components["headers"]["NoStoreCacheControl"];
                    ETag: components["headers"]["LifecycleETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminContentVersion"];
                };
            };
            400: components["responses"]["InvalidArgument"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfValidationFailed"];
            404: components["responses"]["ResourceNotFound"];
            409: components["responses"]["InvalidStateTransition"];
            412: components["responses"]["RevisionMismatch"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    decideDailyContentReview: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 草稿写操作使用响应中的草稿 ETag；生命周期写操作使用内容版本 ETag；
                 *     全局紧急控制使用公开内容开关 ETag。调用方必须原样回传，不能自行拼接。
                 */
                "If-Match": components["parameters"]["IfMatch"];
                /** @description 同一业务意图的网络重试必须复用同一个高熵不透明值。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /**
                 * @description 当前后台会话绑定的随机 CSRF 令牌。后台写操作还必须由服务端校验可信同源 `Origin`；
                 *     令牌只能保存在运行中页面内存，不能放入 localStorage、URL 或日志。
                 */
                "X-CSRF-Token": components["parameters"]["XCsrfToken"];
            };
            path: {
                contentVersion: components["parameters"]["ContentVersionPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewDecisionRequest"];
            };
        };
        responses: {
            200: components["responses"]["LifecycleActionSucceeded"];
            400: components["responses"]["InvalidArgument"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfValidationFailed"];
            404: components["responses"]["ResourceNotFound"];
            409: components["responses"]["InvalidStateTransition"];
            412: components["responses"]["RevisionMismatch"];
            422: components["responses"]["ReviewMissing"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    scheduleDailyContentVersion: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 草稿写操作使用响应中的草稿 ETag；生命周期写操作使用内容版本 ETag；
                 *     全局紧急控制使用公开内容开关 ETag。调用方必须原样回传，不能自行拼接。
                 */
                "If-Match": components["parameters"]["IfMatch"];
                /** @description 同一业务意图的网络重试必须复用同一个高熵不透明值。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /**
                 * @description 当前后台会话绑定的随机 CSRF 令牌。后台写操作还必须由服务端校验可信同源 `Origin`；
                 *     令牌只能保存在运行中页面内存，不能放入 localStorage、URL 或日志。
                 */
                "X-CSRF-Token": components["parameters"]["XCsrfToken"];
            };
            path: {
                contentVersion: components["parameters"]["ContentVersionPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleRequest"];
            };
        };
        responses: {
            200: components["responses"]["LifecycleActionSucceeded"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfValidationFailed"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["RevisionMismatch"];
            422: components["responses"]["PublishPrecheckFailed"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    cancelDailyContentSchedule: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 草稿写操作使用响应中的草稿 ETag；生命周期写操作使用内容版本 ETag；
                 *     全局紧急控制使用公开内容开关 ETag。调用方必须原样回传，不能自行拼接。
                 */
                "If-Match": components["parameters"]["IfMatch"];
                /** @description 同一业务意图的网络重试必须复用同一个高熵不透明值。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /**
                 * @description 当前后台会话绑定的随机 CSRF 令牌。后台写操作还必须由服务端校验可信同源 `Origin`；
                 *     令牌只能保存在运行中页面内存，不能放入 localStorage、URL 或日志。
                 */
                "X-CSRF-Token": components["parameters"]["XCsrfToken"];
            };
            path: {
                contentVersion: components["parameters"]["ContentVersionPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpectedActiveVersionRequest"];
            };
        };
        responses: {
            200: components["responses"]["LifecycleActionSucceeded"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfValidationFailed"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["RevisionMismatch"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    publishDailyContentVersion: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 草稿写操作使用响应中的草稿 ETag；生命周期写操作使用内容版本 ETag；
                 *     全局紧急控制使用公开内容开关 ETag。调用方必须原样回传，不能自行拼接。
                 */
                "If-Match": components["parameters"]["IfMatch"];
                /** @description 同一业务意图的网络重试必须复用同一个高熵不透明值。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /**
                 * @description 当前后台会话绑定的随机 CSRF 令牌。后台写操作还必须由服务端校验可信同源 `Origin`；
                 *     令牌只能保存在运行中页面内存，不能放入 localStorage、URL 或日志。
                 */
                "X-CSRF-Token": components["parameters"]["XCsrfToken"];
            };
            path: {
                contentVersion: components["parameters"]["ContentVersionPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpectedActiveVersionRequest"];
            };
        };
        responses: {
            200: components["responses"]["LifecycleActionSucceeded"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfValidationFailed"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["RevisionMismatch"];
            422: components["responses"]["PublishPrecheckFailed"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    withdrawDailyContentVersion: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 草稿写操作使用响应中的草稿 ETag；生命周期写操作使用内容版本 ETag；
                 *     全局紧急控制使用公开内容开关 ETag。调用方必须原样回传，不能自行拼接。
                 */
                "If-Match": components["parameters"]["IfMatch"];
                /** @description 同一业务意图的网络重试必须复用同一个高熵不透明值。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /**
                 * @description 当前后台会话绑定的随机 CSRF 令牌。后台写操作还必须由服务端校验可信同源 `Origin`；
                 *     令牌只能保存在运行中页面内存，不能放入 localStorage、URL 或日志。
                 */
                "X-CSRF-Token": components["parameters"]["XCsrfToken"];
            };
            path: {
                contentVersion: components["parameters"]["ContentVersionPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WithdrawRequest"];
            };
        };
        responses: {
            200: components["responses"]["LifecycleActionSucceeded"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfValidationFailed"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["RevisionMismatch"];
            422: components["responses"]["PublishPrecheckFailed"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    rollbackDailyContentDay: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 草稿写操作使用响应中的草稿 ETag；生命周期写操作使用内容版本 ETag；
                 *     全局紧急控制使用公开内容开关 ETag。调用方必须原样回传，不能自行拼接。
                 */
                "If-Match": components["parameters"]["IfMatch"];
                /** @description 同一业务意图的网络重试必须复用同一个高熵不透明值。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /**
                 * @description 当前后台会话绑定的随机 CSRF 令牌。后台写操作还必须由服务端校验可信同源 `Origin`；
                 *     令牌只能保存在运行中页面内存，不能放入 localStorage、URL 或日志。
                 */
                "X-CSRF-Token": components["parameters"]["XCsrfToken"];
            };
            path: {
                fortuneDate: components["parameters"]["FortuneDate"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RollbackRequest"];
            };
        };
        responses: {
            200: components["responses"]["LifecycleActionSucceeded"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfValidationFailed"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["RevisionMismatch"];
            422: components["responses"]["PublishPrecheckFailed"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    listAuditEvents: {
        parameters: {
            query?: {
                fortuneDate?: components["parameters"]["FortuneDateQueryOptional"];
                contentVersion?: components["schemas"]["ContentVersion"];
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 返回审计记录 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    "Cache-Control": components["headers"]["NoStoreCacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventPage"];
                };
            };
            400: components["responses"]["InvalidArgument"];
            401: components["responses"]["Unauthenticated"];
        };
    };
}
