/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取服务端当前命理日的已发布内容
         * @description 服务端按 `Asia/Shanghai` 一次性计算完整 `requestContext`。
         *     网页不得使用设备时钟重新计算 `civilDate`、`fortuneDate` 或 `shichen`。
         */
        get: operations["getToday"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/daily/{fortuneDate}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取指定命理日当前安全的公开内容
         * @description 用于分享落地页和既有日期链接，不表示产品提供历史浏览入口。
         *     如果调用方提供的预期版本已经被替换、回滚或下线，服务端返回当前安全版本，
         *     并在 `resolution` 中说明发生了版本变化。
         */
        get: operations["getDailyContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/daily/{fortuneDate}/looks/{lookId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取指定内容版本中的穿搭详情 */
        get: operations["getLookDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/poster-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 获取已有海报或创建海报渲染任务
         * @description 海报只使用已经发布的内容、已审核图片和已冻结模板，不调用 AI 生图。
         *     相同业务意图的网络重试必须复用同一个 `Idempotency-Key`。
         */
        post: operations["createPosterJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/poster-jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询海报任务状态 */
        get: operations["getPosterJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback-reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 提交内容纠错或产品建议 */
        post: operations["createFeedbackReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/daily-content-drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建某个命理日的草稿 */
        post: operations["createDailyContentDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/daily-content-drafts/{draftId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查看草稿 */
        get: operations["getDailyContentDraft"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/daily-content-drafts/{draftId}/modules/{moduleCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 修改草稿中的一个内容模块
         * @description 只允许修改 `draft`。请求体必须与路径中的 `moduleCode` 对应。
         *     成功后服务端增加 `draftRevision` 并返回新的草稿 ETag。
         */
        patch: operations["updateDailyContentDraftModule"];
        trace?: never;
    };
    "/admin/api/v1/daily-content-drafts/{draftId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 冻结草稿并创建不可修改的内容版本 */
        post: operations["submitDailyContentDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/daily-content-versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查看某命理日的全部内容版本 */
        get: operations["listDailyContentVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/daily-content-versions/{contentVersion}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查看不可变内容、状态、检查和大师确认依据 */
        get: operations["getDailyContentVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/daily-content-versions/{contentVersion}/master-review-evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登记大师在系统外留下的确认依据 */
        post: operations["addMasterReviewEvidence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/daily-content-versions/{contentVersion}/review-decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 运行必审检查并批准或退回当前内容版本 */
        post: operations["decideDailyContentReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/daily-content-versions/{contentVersion}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 安排内容版本在指定时间上线 */
        post: operations["scheduleDailyContentVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/daily-content-versions/{contentVersion}/cancel-schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 取消未生效排期并回到 `approved` */
        post: operations["cancelDailyContentSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/daily-content-versions/{contentVersion}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 立即发布已批准的内容版本 */
        post: operations["publishDailyContentVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/daily-content-versions/{contentVersion}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 下线当前版本并可同时恢复安全旧版本 */
        post: operations["withdrawDailyContentVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/daily-content-days/{fortuneDate}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 恢复同一命理日曾经发布且仍安全的旧版本 */
        post: operations["rollbackDailyContentDay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/v1/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询内容生命周期审计记录 */
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: date
         * @description Five 命理日；北京时间 23:00 进入下一命理日。
         * @example 2026-07-15
         */
        FortuneDate: string;
        /**
         * Format: date-time
         * @example 2026-07-14T23:30:00+08:00
         */
        ZonedDateTime: string;
        /**
         * @description 不透明内容版本；调用方只能比较相等，不得解析。
         * @example fd-20260715-r3
         */
        ContentVersion: string;
        /** @description 不透明标识；调用方不得解析。 */
        OpaqueId: string;
        NullableContentVersion: components["schemas"]["ContentVersion"] | null;
        /** @enum {string} */
        ElementCode: "wood" | "fire" | "earth" | "metal" | "water";
        /** @enum {string} */
        TierCode: "da_ji" | "ci_ji" | "ping" | "jiao_cha" | "bu_li";
        /** @enum {string} */
        ContentState: "draft" | "in_review" | "changes_requested" | "approved" | "scheduled" | "published" | "superseded" | "withdrawn";
        /** @enum {string} */
        ModuleCode: "calendar_algorithm" | "copy_and_formula" | "visual_and_rights" | "poster_consistency";
        RequestContext: {
            responseGeneratedAt: components["schemas"]["ZonedDateTime"];
            /** Format: date */
            civilDate: string;
            fortuneDate: components["schemas"]["FortuneDate"];
            /** @enum {string} */
            shichen: "子" | "丑" | "寅" | "卯" | "辰" | "巳" | "午" | "未" | "申" | "酉" | "戌" | "亥";
            /** @constant */
            timezone: "Asia/Shanghai";
            /** @constant */
            dayBoundary: "23:00";
            crossedDayBoundary: boolean;
        };
        CalendarInfo: {
            weekdayText: string;
            lunarDateText: string;
            ganzhiDay: string;
            /** @enum {string} */
            branch: "子" | "丑" | "寅" | "卯" | "辰" | "巳" | "午" | "未" | "申" | "酉" | "戌" | "亥";
            dayElement: components["schemas"]["ElementCode"];
            /** @enum {string} */
            dayElementLabel: "木" | "火" | "土" | "金" | "水";
        };
        ColorRef: {
            colorCode: string;
            name: string;
        };
        Tier: {
            rank: number;
            tierCode: components["schemas"]["TierCode"];
            /** @enum {string} */
            algorithmLabel: "大吉" | "次吉" | "平" | "较差" | "不利";
            /** @enum {string} */
            displayLabel: "今日优先" | "稳妥选择" | "日常可穿" | "注意";
            /**
             * @description 大吉、次吉、平为 `primary`；较差和不利为 `attention`。
             *     网页按此字段合并展示，不自行重算五行关系。
             * @enum {string}
             */
            displaySection: "primary" | "attention";
            element: components["schemas"]["ElementCode"];
            /** @enum {string} */
            elementLabel: "木" | "火" | "土" | "金" | "水";
            colors: components["schemas"]["ColorRef"][];
            relationText: string;
            explanation: string;
        };
        BalanceSuggestion: {
            /** @constant */
            title: "已经穿了注意色";
            description: string;
            /** @constant */
            preferredTierCode: "da_ji";
            accessoryExamples: string[];
        };
        Scenario: {
            code: string;
            label: string;
        };
        Audience: {
            code: string;
            label: string;
        };
        OutfitSlot: {
            /** @enum {string} */
            role: "primary" | "secondary" | "accent";
            /** @enum {string} */
            roleLabel: "主色" | "辅助色" | "点缀色";
            tierCode: components["schemas"]["TierCode"];
            colorCodes: string[];
            ratioPercent: number | null;
            garmentParts: string[];
        };
        OutfitFormula: {
            formulaId: components["schemas"]["OpaqueId"];
            /** @enum {string} */
            kind: "mono" | "dual" | "triple";
            title: string;
            scenario: components["schemas"]["Scenario"];
            audience: components["schemas"]["Audience"];
            slots: components["schemas"]["OutfitSlot"][];
            lookIds: components["schemas"]["OpaqueId"][];
            disclaimer: string;
        };
        PublicImageAsset: {
            assetId: components["schemas"]["OpaqueId"];
            /** Format: uri */
            url: string;
            width: number;
            height: number;
            /** @enum {string} */
            mediaType: "image/avif" | "image/webp" | "image/jpeg" | "image/png";
            altText: string;
            aiGenerated: boolean;
            aiDisclosure: string | null;
        };
        GarmentItem: {
            /** @enum {string} */
            category: "top" | "bottom" | "dress" | "outerwear" | "shoes" | "bag" | "accessory";
            categoryLabel: string;
            colorCode: string;
            description: string;
        };
        LookAlternative: {
            replaceCategory: string;
            description: string;
        };
        PublicLook: {
            lookId: components["schemas"]["OpaqueId"];
            formulaId: components["schemas"]["OpaqueId"];
            requiredForPublish: boolean;
            sortOrder: number;
            title: string;
            scenario: components["schemas"]["Scenario"];
            audience: components["schemas"]["Audience"];
            coverImage: components["schemas"]["PublicImageAsset"];
            detailImages: components["schemas"]["PublicImageAsset"][];
            items: components["schemas"]["GarmentItem"][];
            alternatives: components["schemas"]["LookAlternative"][];
        };
        Basis: {
            steps: string[];
            disclaimer: string;
        };
        ShareContent: {
            summaryText: string;
            copyText: string;
            posterTemplateVersion: string;
            /** @constant */
            posterJobEndpoint: "/api/v1/poster-jobs";
        };
        ContentVersionSet: {
            contentVersion: components["schemas"]["ContentVersion"];
            calendarDataVersion: string;
            calendarRuleVersion: string;
            algorithmVersion: string;
            copyVersion: string;
            outfitVersion: string;
            assetManifestVersion: string;
            posterTemplateVersion: string;
        };
        DailyContent: {
            fortuneDate: components["schemas"]["FortuneDate"];
            effectiveFrom: components["schemas"]["ZonedDateTime"];
            effectiveTo: components["schemas"]["ZonedDateTime"];
            calendar: components["schemas"]["CalendarInfo"];
            tiers: components["schemas"]["Tier"][];
            balanceSuggestion: components["schemas"]["BalanceSuggestion"];
            outfitFormulas: components["schemas"]["OutfitFormula"][];
            /** @description 恰好两项 `requiredForPublish=true`，第三项如果存在必须为可选。 */
            looks: components["schemas"]["PublicLook"][];
            basis: components["schemas"]["Basis"];
            share: components["schemas"]["ShareContent"];
            versions: components["schemas"]["ContentVersionSet"];
        };
        TodayResponse: {
            requestContext: components["schemas"]["RequestContext"];
            content: components["schemas"]["DailyContent"];
        };
        VersionResolution: {
            expectedContentVersion: components["schemas"]["NullableContentVersion"];
            servedContentVersion: components["schemas"]["ContentVersion"];
            versionChanged: boolean;
            /** @enum {string} */
            reason: "current" | "replaced" | "rolled_back" | "withdrawn";
        };
        DailyContentResponse: {
            requestedFortuneDate: components["schemas"]["FortuneDate"];
            content: components["schemas"]["DailyContent"];
            resolution: components["schemas"]["VersionResolution"];
        };
        LookDetailResponse: {
            fortuneDate: components["schemas"]["FortuneDate"];
            contentVersion: components["schemas"]["ContentVersion"];
            look: components["schemas"]["PublicLook"];
        };
        CreatePosterJobRequest: {
            fortuneDate: components["schemas"]["FortuneDate"];
            expectedContentVersion: components["schemas"]["ContentVersion"];
            channelId: string;
        };
        PosterEntry: {
            /** @constant */
            type: "web_qr";
            /** Format: uri */
            landingUrl: string;
        };
        PosterJob: {
            jobId: components["schemas"]["OpaqueId"];
            /** @enum {string} */
            status: "processing" | "ready" | "failed" | "version_changed";
            sourceContentVersion: components["schemas"]["ContentVersion"];
            currentActiveContentVersion: components["schemas"]["NullableContentVersion"];
            posterTemplateVersion: string;
            posterInstanceId: components["schemas"]["OpaqueId"] | null;
            channelId: string;
            assetUrl: string | null;
            entry: components["schemas"]["PosterEntry"] | null;
        };
        CreateFeedbackRequest: {
            /** @enum {string} */
            category: "content_error" | "product_feedback";
            message: string;
            fortuneDate: components["schemas"]["FortuneDate"];
            contentVersion: components["schemas"]["ContentVersion"];
            channelId: string;
            /** @description 只有用户单独同意后才可填写。 */
            contact: string | null;
        };
        CreateFeedbackResponse: {
            feedbackId: components["schemas"]["OpaqueId"];
            /** @constant */
            status: "received";
        };
        DraftRevision: number;
        LifecycleRevision: number;
        CalendarAlgorithmModule: {
            calendar: components["schemas"]["CalendarInfo"];
            tiers: components["schemas"]["Tier"][];
            calendarDataVersion: string;
            calendarRuleVersion: string;
            algorithmVersion: string;
        };
        CopyAndFormulaModule: {
            balanceSuggestion: components["schemas"]["BalanceSuggestion"];
            outfitFormulas: components["schemas"]["OutfitFormula"][];
            basis: components["schemas"]["Basis"];
            share: components["schemas"]["ShareContent"];
            copyVersion: string;
            outfitVersion: string;
        };
        /** @enum {string} */
        ImageRightsStatus: "pending" | "cleared" | "rejected" | "revoked";
        /** @enum {string} */
        ImageReviewStatus: "pending" | "approved" | "rejected" | "withdrawn";
        /** @enum {string} */
        AiLabelStatus: "not_applicable" | "pending" | "complete" | "failed";
        AdminImageAsset: {
            assetId: components["schemas"]["OpaqueId"];
            /** @description 上传完成前可为空；公开响应只返回已经审核通过的不可变 URL。 */
            fileUrl: string | null;
            width: number;
            height: number;
            /** @enum {string} */
            mediaType: "image/avif" | "image/webp" | "image/jpeg" | "image/png";
            altText: string;
            sha256: string;
            /** @enum {string} */
            sourceType: "licensed" | "ai_generated" | "fallback_template";
            declaredModel: string | null;
            promptVersion: string | null;
            generatedAt: components["schemas"]["ZonedDateTime"] | null;
            reviewStatus: components["schemas"]["ImageReviewStatus"];
            rightsStatus: components["schemas"]["ImageRightsStatus"];
            aiLabelStatus: components["schemas"]["AiLabelStatus"];
            rightsRecordIds: components["schemas"]["OpaqueId"][];
        };
        LookDraft: {
            lookId: components["schemas"]["OpaqueId"];
            formulaId: components["schemas"]["OpaqueId"];
            requiredForPublish: boolean;
            sortOrder: number;
            title: string;
            scenario: components["schemas"]["Scenario"];
            audience: components["schemas"]["Audience"];
            coverAssetId: components["schemas"]["OpaqueId"];
            detailAssetIds: components["schemas"]["OpaqueId"][];
            items: components["schemas"]["GarmentItem"][];
            alternatives: components["schemas"]["LookAlternative"][];
        };
        RightsRecord: {
            rightsRecordId: components["schemas"]["OpaqueId"];
            /** @enum {string} */
            kind: "license" | "terms_snapshot" | "purchase_receipt" | "consent" | "internal_record";
            reference: string;
            recordedAt: components["schemas"]["ZonedDateTime"];
        };
        VisualAndRightsModule: {
            looks: components["schemas"]["LookDraft"][];
            assets: components["schemas"]["AdminImageAsset"][];
            rightsRecords: components["schemas"]["RightsRecord"][];
            assetManifestVersion: string;
        };
        PosterConsistencyModule: {
            posterTemplateVersion: string;
            templateId: components["schemas"]["OpaqueId"];
            sampleAssetId: components["schemas"]["OpaqueId"];
        };
        DraftModules: {
            calendar_algorithm: components["schemas"]["CalendarAlgorithmModule"] | null;
            copy_and_formula: components["schemas"]["CopyAndFormulaModule"] | null;
            visual_and_rights: components["schemas"]["VisualAndRightsModule"] | null;
            poster_consistency: components["schemas"]["PosterConsistencyModule"] | null;
        };
        ContentDraft: {
            draftId: components["schemas"]["OpaqueId"];
            fortuneDate: components["schemas"]["FortuneDate"];
            /** @constant */
            state: "draft";
            draftRevision: components["schemas"]["DraftRevision"];
            modules: components["schemas"]["DraftModules"];
            createdAt: components["schemas"]["ZonedDateTime"];
            updatedAt: components["schemas"]["ZonedDateTime"];
        };
        CreateDraftRequest: {
            fortuneDate: components["schemas"]["FortuneDate"];
            copyFromContentVersion: components["schemas"]["NullableContentVersion"];
        };
        DraftModuleUpdate: components["schemas"]["CalendarAlgorithmModule"] | components["schemas"]["CopyAndFormulaModule"] | components["schemas"]["VisualAndRightsModule"] | components["schemas"]["PosterConsistencyModule"];
        UpdatedDraftModule: {
            draftId: components["schemas"]["OpaqueId"];
            moduleCode: components["schemas"]["ModuleCode"];
            draftRevision: components["schemas"]["DraftRevision"];
            module: components["schemas"]["DraftModuleUpdate"];
        };
        SubmitDraftResult: {
            draftId: components["schemas"]["OpaqueId"];
            contentVersion: components["schemas"]["ContentVersion"];
            /** @constant */
            state: "in_review";
            lifecycleRevision: components["schemas"]["LifecycleRevision"];
        };
        PreflightCheck: {
            /** @enum {string} */
            code: "calendar_algorithm" | "calendar_golden_data" | "master_review_evidence" | "copy_and_formula" | "required_images" | "visual_and_rights" | "ai_label" | "poster_consistency" | "reference_integrity";
            /** @enum {string} */
            status: "pending" | "passed" | "failed";
            message: string;
        };
        EvidenceReference: {
            /** @enum {string} */
            kind: "attachment" | "message_link" | "document" | "note";
            reference: string;
        };
        MasterReviewEvidence: {
            evidenceId: components["schemas"]["OpaqueId"];
            reviewerDisplayName: string;
            reviewedAt: components["schemas"]["ZonedDateTime"];
            /** @enum {string} */
            conclusion: "confirmed" | "changes_requested";
            notes: string;
            references: components["schemas"]["EvidenceReference"][];
        };
        AddMasterReviewEvidenceRequest: {
            reviewerDisplayName: string;
            reviewedAt: components["schemas"]["ZonedDateTime"];
            /** @enum {string} */
            conclusion: "confirmed" | "changes_requested";
            notes: string;
            references: components["schemas"]["EvidenceReference"][];
        };
        ContentVersionSummary: {
            contentVersion: components["schemas"]["ContentVersion"];
            state: components["schemas"]["ContentState"];
            lifecycleRevision: components["schemas"]["LifecycleRevision"];
            createdAt: components["schemas"]["ZonedDateTime"];
            effectiveFrom: components["schemas"]["ZonedDateTime"] | null;
            effectiveTo: components["schemas"]["ZonedDateTime"] | null;
        };
        AdminContentVersion: {
            contentVersion: components["schemas"]["ContentVersion"];
            fortuneDate: components["schemas"]["FortuneDate"];
            state: components["schemas"]["ContentState"];
            lifecycleRevision: components["schemas"]["LifecycleRevision"];
            activeContentVersion: components["schemas"]["NullableContentVersion"];
            snapshot: components["schemas"]["DraftModules"];
            preflightChecks: components["schemas"]["PreflightCheck"][];
            masterReviewEvidence: components["schemas"]["MasterReviewEvidence"][];
        };
        ReviewDecisionRequest: {
            /** @enum {string} */
            decision: "approved" | "changes_requested";
            /** @description `changes_requested` 时必须填写。 */
            reason: string | null;
        };
        ExpectedActiveVersionRequest: {
            expectedActiveContentVersion: components["schemas"]["NullableContentVersion"];
            reason: string;
        };
        ScheduleRequest: {
            expectedActiveContentVersion: components["schemas"]["NullableContentVersion"];
            reason: string;
            effectiveFrom: components["schemas"]["ZonedDateTime"];
        };
        WithdrawRequest: {
            expectedActiveContentVersion: components["schemas"]["NullableContentVersion"];
            reason: string;
            replacementContentVersion: components["schemas"]["NullableContentVersion"];
        };
        RollbackRequest: {
            expectedActiveContentVersion: components["schemas"]["NullableContentVersion"];
            reason: string;
            targetContentVersion: components["schemas"]["ContentVersion"];
        };
        StateTransition: {
            contentVersion: components["schemas"]["ContentVersion"];
            fromState: components["schemas"]["ContentState"];
            toState: components["schemas"]["ContentState"];
        };
        LifecycleActionResult: {
            fortuneDate: components["schemas"]["FortuneDate"];
            contentVersion: components["schemas"]["ContentVersion"];
            state: components["schemas"]["ContentState"];
            lifecycleRevision: components["schemas"]["LifecycleRevision"];
            activeContentVersion: components["schemas"]["NullableContentVersion"];
            transitions: components["schemas"]["StateTransition"][];
            auditEventId: components["schemas"]["OpaqueId"];
        };
        AuditEvent: {
            auditEventId: components["schemas"]["OpaqueId"];
            action: string;
            occurredAt: components["schemas"]["ZonedDateTime"];
            requestId: string;
            fortuneDate: components["schemas"]["FortuneDate"];
            contentVersion: components["schemas"]["ContentVersion"];
            reason: string;
        };
        AuditEventPage: {
            items: components["schemas"]["AuditEvent"][];
            nextCursor: string | null;
        };
        /** @enum {string} */
        ErrorCode: "INVALID_ARGUMENT" | "INVALID_FORTUNE_DATE" | "UNAUTHENTICATED" | "FORBIDDEN" | "RESOURCE_NOT_FOUND" | "CONTENT_NOT_FOUND" | "LOOK_NOT_FOUND" | "CONTENT_VERSION_CHANGED" | "ACTIVE_CONTENT_VERSION_CHANGED" | "IDEMPOTENCY_KEY_REUSED" | "INVALID_STATE_TRANSITION" | "VERSION_WITHDRAWN" | "HISTORICAL_CONTENT_EXPIRED" | "REVISION_MISMATCH" | "REQUIRED_REVIEW_MISSING" | "MASTER_REVIEW_EVIDENCE_MISSING" | "PUBLISH_PRECHECK_FAILED" | "SCHEDULE_TIME_INVALID" | "PRECONDITION_REQUIRED" | "RATE_LIMITED" | "CONTENT_NOT_READY" | "POSTER_GENERATION_UNAVAILABLE";
        Error: {
            code: components["schemas"]["ErrorCode"];
            message: string;
            retryable: boolean;
            requestId: string;
            details: {
                [key: string]: unknown;
            };
        };
        ErrorEnvelope: {
            error: components["schemas"]["Error"];
        };
    };
    responses: {
        /** @description 请求字段或格式无效 */
        InvalidArgument: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 命理日格式或允许范围无效 */
        InvalidFortuneDate: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 后台会话不存在或已失效 */
        Unauthenticated: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 幂等键、活跃版本或状态发生冲突 */
        Conflict: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 指定命理日没有可公开内容 */
        ContentNotFound: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 搭配不存在于当前内容版本 */
        LookNotFound: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 后台资源或任务不存在 */
        ResourceNotFound: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 网页持有的内容版本不是当前活跃版本 */
        ContentVersionChanged: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                "X-Content-Version": components["headers"]["XContentVersion"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 当前状态不允许执行该动作 */
        InvalidStateTransition: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 指定日期的公开内容超过保留期 */
        HistoricalContentExpired: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description `If-Match` 不是资源当前修订号 */
        RevisionMismatch: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                /** @description 当前资源 ETag，调用方必须刷新后再操作。 */
                ETag?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 大师依据或必审检查不完整 */
        ReviewMissing: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 发布、排期或恢复检查未通过 */
        PublishPrecheckFailed: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 需要并发保护的写操作缺少 `If-Match` */
        PreconditionRequired: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 请求过于频繁 */
        RateLimited: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 当前命理日还没有可公开内容 */
        ContentNotReady: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 海报暂时不可用，基础每日内容不受影响 */
        PosterUnavailable: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 状态变化已在一个事务中完成 */
        LifecycleActionSucceeded: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                ETag: components["headers"]["LifecycleETag"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["LifecycleActionResult"];
            };
        };
    };
    parameters: {
        FortuneDate: components["schemas"]["FortuneDate"];
        FortuneDateQuery: components["schemas"]["FortuneDate"];
        FortuneDateQueryOptional: components["schemas"]["FortuneDate"];
        LookId: components["schemas"]["OpaqueId"];
        JobId: components["schemas"]["OpaqueId"];
        DraftId: components["schemas"]["OpaqueId"];
        ContentVersionPath: components["schemas"]["ContentVersion"];
        ModuleCode: components["schemas"]["ModuleCode"];
        ExpectedContentVersionOptional: components["schemas"]["ContentVersion"];
        ExpectedContentVersionRequired: components["schemas"]["ContentVersion"];
        /**
         * @description 草稿写操作使用响应中的草稿 ETag；生命周期写操作使用内容版本 ETag。
         *     调用方必须原样回传，不能自行拼接。
         */
        IfMatch: string;
        /** @description 同一业务意图的网络重试必须复用同一个高熵不透明值。 */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: {
        /** @description 当前外部请求的追踪编号；缓存命中时也必须按请求生成。 */
        XRequestId: string;
        /** @description 当前响应中的业务内容版本。 */
        XContentVersion: components["schemas"]["ContentVersion"];
        /** @description 完整 HTTP 响应表示的校验值，与 `contentVersion` 不是同一概念。 */
        RepresentationETag: string;
        /** @description 草稿当前修订号的强 ETag，例如 `"draft:7"`。 */
        DraftETag: string;
        /** @description 内容生命周期当前修订号的强 ETag，例如 `"lifecycle:12"`。 */
        LifecycleETag: string;
        /**
         * @description `public, max-age=0, s-maxage=N, must-revalidate`。
         *     N 是 60 秒、内容结束、下一时辰和下一民用午夜剩余秒数中的最小值。
         */
        DynamicCacheControl: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getToday: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前命理日存在可以公开读取的内容 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    "X-Content-Version": components["headers"]["XContentVersion"];
                    ETag: components["headers"]["RepresentationETag"];
                    "Cache-Control": components["headers"]["DynamicCacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayResponse"];
                };
            };
            /** @description `If-None-Match` 对应的完整响应表示仍有效 */
            304: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    ETag: components["headers"]["RepresentationETag"];
                    "Cache-Control": components["headers"]["DynamicCacheControl"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["RateLimited"];
            503: components["responses"]["ContentNotReady"];
        };
    };
    getDailyContent: {
        parameters: {
            query?: {
                expectedContentVersion?: components["parameters"]["ExpectedContentVersionOptional"];
            };
            header?: never;
            path: {
                fortuneDate: components["parameters"]["FortuneDate"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 返回指定日期当前安全的公开内容 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    "X-Content-Version": components["headers"]["XContentVersion"];
                    ETag: components["headers"]["RepresentationETag"];
                    "Cache-Control": components["headers"]["DynamicCacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyContentResponse"];
                };
            };
            400: components["responses"]["InvalidFortuneDate"];
            404: components["responses"]["ContentNotFound"];
            410: components["responses"]["HistoricalContentExpired"];
        };
    };
    getLookDetail: {
        parameters: {
            query: {
                expectedContentVersion: components["parameters"]["ExpectedContentVersionRequired"];
            };
            header?: never;
            path: {
                fortuneDate: components["parameters"]["FortuneDate"];
                lookId: components["parameters"]["LookId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 返回与预期内容版本一致的穿搭详情 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    "X-Content-Version": components["headers"]["XContentVersion"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LookDetailResponse"];
                };
            };
            400: components["responses"]["InvalidFortuneDate"];
            404: components["responses"]["LookNotFound"];
            409: components["responses"]["ContentVersionChanged"];
        };
    };
    createPosterJob: {
        parameters: {
            query?: never;
            header: {
                /** @description 同一业务意图的网络重试必须复用同一个高熵不透明值。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePosterJobRequest"];
            };
        };
        responses: {
            /** @description 已有相同海报实例 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PosterJob"];
                };
            };
            /** @description 已接受新的渲染任务 */
            202: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PosterJob"];
                };
            };
            /** @description 内容版本已变化或幂等键被用于另一请求 */
            409: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
            503: components["responses"]["PosterUnavailable"];
        };
    };
    getPosterJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 返回当前任务状态 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PosterJob"];
                };
            };
            404: components["responses"]["ResourceNotFound"];
        };
    };
    createFeedbackReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFeedbackRequest"];
            };
        };
        responses: {
            /** @description 已接收反馈 */
            202: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateFeedbackResponse"];
                };
            };
            400: components["responses"]["InvalidArgument"];
            429: components["responses"]["RateLimited"];
        };
    };
    createDailyContentDraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDraftRequest"];
            };
        };
        responses: {
            /** @description 已创建草稿 */
            201: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    ETag: components["headers"]["DraftETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentDraft"];
                };
            };
            400: components["responses"]["InvalidArgument"];
            401: components["responses"]["Unauthenticated"];
            409: components["responses"]["Conflict"];
        };
    };
    getDailyContentDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draftId: components["parameters"]["DraftId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 返回草稿及当前修订号 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    ETag: components["headers"]["DraftETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentDraft"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["ResourceNotFound"];
        };
    };
    updateDailyContentDraftModule: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 草稿写操作使用响应中的草稿 ETag；生命周期写操作使用内容版本 ETag。
                 *     调用方必须原样回传，不能自行拼接。
                 */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                draftId: components["parameters"]["DraftId"];
                moduleCode: components["parameters"]["ModuleCode"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftModuleUpdate"];
            };
        };
        responses: {
            /** @description 返回更新后的模块和草稿修订号 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    ETag: components["headers"]["DraftETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdatedDraftModule"];
                };
            };
            400: components["responses"]["InvalidArgument"];
            401: components["responses"]["Unauthenticated"];
            409: components["responses"]["InvalidStateTransition"];
            412: components["responses"]["RevisionMismatch"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    submitDailyContentDraft: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 草稿写操作使用响应中的草稿 ETag；生命周期写操作使用内容版本 ETag。
                 *     调用方必须原样回传，不能自行拼接。
                 */
                "If-Match": components["parameters"]["IfMatch"];
                /** @description 同一业务意图的网络重试必须复用同一个高熵不透明值。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                draftId: components["parameters"]["DraftId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已创建 `in_review` 内容版本 */
            201: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    ETag: components["headers"]["LifecycleETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitDraftResult"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["RevisionMismatch"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    listDailyContentVersions: {
        parameters: {
            query: {
                fortuneDate: components["parameters"]["FortuneDateQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 按创建时间倒序返回版本 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        fortuneDate: components["schemas"]["FortuneDate"];
                        activeContentVersion: components["schemas"]["ContentVersion"] | null;
                        items: components["schemas"]["ContentVersionSummary"][];
                    };
                };
            };
            400: components["responses"]["InvalidFortuneDate"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    getDailyContentVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contentVersion: components["parameters"]["ContentVersionPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 返回一个完整内容版本 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    ETag: components["headers"]["LifecycleETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminContentVersion"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["ResourceNotFound"];
        };
    };
    addMasterReviewEvidence: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 草稿写操作使用响应中的草稿 ETag；生命周期写操作使用内容版本 ETag。
                 *     调用方必须原样回传，不能自行拼接。
                 */
                "If-Match": components["parameters"]["IfMatch"];
                /** @description 同一业务意图的网络重试必须复用同一个高熵不透明值。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                contentVersion: components["parameters"]["ContentVersionPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMasterReviewEvidenceRequest"];
            };
        };
        responses: {
            /** @description 已登记依据并增加生命周期修订号 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    ETag: components["headers"]["LifecycleETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminContentVersion"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            409: components["responses"]["InvalidStateTransition"];
            412: components["responses"]["RevisionMismatch"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    decideDailyContentReview: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 草稿写操作使用响应中的草稿 ETag；生命周期写操作使用内容版本 ETag。
                 *     调用方必须原样回传，不能自行拼接。
                 */
                "If-Match": components["parameters"]["IfMatch"];
                /** @description 同一业务意图的网络重试必须复用同一个高熵不透明值。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                contentVersion: components["parameters"]["ContentVersionPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewDecisionRequest"];
            };
        };
        responses: {
            200: components["responses"]["LifecycleActionSucceeded"];
            401: components["responses"]["Unauthenticated"];
            409: components["responses"]["InvalidStateTransition"];
            412: components["responses"]["RevisionMismatch"];
            422: components["responses"]["ReviewMissing"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    scheduleDailyContentVersion: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 草稿写操作使用响应中的草稿 ETag；生命周期写操作使用内容版本 ETag。
                 *     调用方必须原样回传，不能自行拼接。
                 */
                "If-Match": components["parameters"]["IfMatch"];
                /** @description 同一业务意图的网络重试必须复用同一个高熵不透明值。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                contentVersion: components["parameters"]["ContentVersionPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleRequest"];
            };
        };
        responses: {
            200: components["responses"]["LifecycleActionSucceeded"];
            401: components["responses"]["Unauthenticated"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["RevisionMismatch"];
            422: components["responses"]["PublishPrecheckFailed"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    cancelDailyContentSchedule: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 草稿写操作使用响应中的草稿 ETag；生命周期写操作使用内容版本 ETag。
                 *     调用方必须原样回传，不能自行拼接。
                 */
                "If-Match": components["parameters"]["IfMatch"];
                /** @description 同一业务意图的网络重试必须复用同一个高熵不透明值。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                contentVersion: components["parameters"]["ContentVersionPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpectedActiveVersionRequest"];
            };
        };
        responses: {
            200: components["responses"]["LifecycleActionSucceeded"];
            401: components["responses"]["Unauthenticated"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["RevisionMismatch"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    publishDailyContentVersion: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 草稿写操作使用响应中的草稿 ETag；生命周期写操作使用内容版本 ETag。
                 *     调用方必须原样回传，不能自行拼接。
                 */
                "If-Match": components["parameters"]["IfMatch"];
                /** @description 同一业务意图的网络重试必须复用同一个高熵不透明值。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                contentVersion: components["parameters"]["ContentVersionPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpectedActiveVersionRequest"];
            };
        };
        responses: {
            200: components["responses"]["LifecycleActionSucceeded"];
            401: components["responses"]["Unauthenticated"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["RevisionMismatch"];
            422: components["responses"]["PublishPrecheckFailed"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    withdrawDailyContentVersion: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 草稿写操作使用响应中的草稿 ETag；生命周期写操作使用内容版本 ETag。
                 *     调用方必须原样回传，不能自行拼接。
                 */
                "If-Match": components["parameters"]["IfMatch"];
                /** @description 同一业务意图的网络重试必须复用同一个高熵不透明值。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                contentVersion: components["parameters"]["ContentVersionPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WithdrawRequest"];
            };
        };
        responses: {
            200: components["responses"]["LifecycleActionSucceeded"];
            401: components["responses"]["Unauthenticated"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["RevisionMismatch"];
            422: components["responses"]["PublishPrecheckFailed"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    rollbackDailyContentDay: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description 草稿写操作使用响应中的草稿 ETag；生命周期写操作使用内容版本 ETag。
                 *     调用方必须原样回传，不能自行拼接。
                 */
                "If-Match": components["parameters"]["IfMatch"];
                /** @description 同一业务意图的网络重试必须复用同一个高熵不透明值。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                fortuneDate: components["parameters"]["FortuneDate"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RollbackRequest"];
            };
        };
        responses: {
            200: components["responses"]["LifecycleActionSucceeded"];
            401: components["responses"]["Unauthenticated"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["RevisionMismatch"];
            422: components["responses"]["PublishPrecheckFailed"];
            428: components["responses"]["PreconditionRequired"];
        };
    };
    listAuditEvents: {
        parameters: {
            query?: {
                fortuneDate?: components["parameters"]["FortuneDateQueryOptional"];
                contentVersion?: components["schemas"]["ContentVersion"];
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 返回审计记录 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventPage"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
}
