export const ADMIN_AUTH_SERVICE = Symbol("ADMIN_AUTH_SERVICE");
export const CONTENT_LIFECYCLE_SERVICE = Symbol("CONTENT_LIFECYCLE_SERVICE");
export const DAILY_IMAGE_ASSET_SERVICE = Symbol("DAILY_IMAGE_ASSET_SERVICE");
export const EMERGENCY_CONTROL_SERVICE = Symbol("EMERGENCY_CONTROL_SERVICE");
